config/routes.rb
Rails.application.routes.draw do
 devise_for :admin_users, controllers: {
    sessions: 'admin_user/sessions',
    passwords: 'admin_user/passwords'
  }
  #get 'bookings/create'
  root 'home#index'
  resources :workshops, only: %i[index show]
  resources :bookings, only: %i[create] do
  	get :booking_details, on: :member
  end

  resources :refunds do
    get :refund_acceptance, on: :member
  end
  

  namespace :admin do
  	 get 'dashboard' => 'dashboard#index'
     resources :workshops
     resources :bookings
     resources :customers
     resources :refunds do 
      member do
        patch :process_refund
      end
     end
  	end
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :refunds
  belongs_to :customer
  belongs_to :workshop

  validates :order_number, presence: true, uniqueness: true

  before_validation :generate_order_number
  after_create :update_workshop_sit_count

  def update_workshop_sit_count
    workshop.update(remaining_sits: workshop.total_sits - no_of_tickets)
  end

  def generate_order_number
  	self.order_number = "BOOKING-#{SecureRandom.hex(5).upcase}"
  end

  def is_refundable?
    workshop.start_date > Date.today
  end
end

app/controllers/admin/bookings_controller.rb
class Admin::BookingsController < AdminController
  before_action :set_booking_with_parents, only: %i[show destroy]

  def index
    @q = Booking.ransack(params[:q])
    @bookings = @q.result.includes(:customer, :workshop)
  end

  def show
  end

  def destroy
    @booking.destroy
    redirect_to admin_bookings_path, notice: 'Booking deleted successfully'
  end

  private

  def set_booking_with_parents
    #debugger
    @booking = Booking.find(params[:id])
    @customer = @booking.customer
    @workshop = @booking.workshop
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @stripe_service = StripeService.new
    @workshop = Workshop.find(params[:workshop_id])
    @customer = Customer.find_by(email_id: params[:email_id])
    unless @customer.present?
      @customer = Customer.create(customer_params)
    end

    @stripe_customer = @stripe_service.find_or_create_customer(@customer)

    @card = @stripe_service.create_stripe_customer_card(card_token_params, @stripe_customer)

    @amount_to_be_paid = params[:no_of_tickets].to_i * @workshop.registration_fee

    @charge = @stripe_service.create_stripe_charge(@amount_to_be_paid, @stripe_customer.id, @card.id, @workshop)

    @booking = @workshop.bookings.create(
      customer_id: @customer.id,
      stripe_transaction_id: @charge.id,
      no_of_tickets: params[:no_of_tickets].to_i,
      amount_paid: @amount_to_be_paid
    )
    BookingsMailer.booking_confirmation(@booking).deliver_now

    redirect_to workshop_path(@workshop), notice: 'Your tickets has been booked'
     rescue Stripe::StripeError => error
    redirect_to workshop_path(@workshop), alert: "#{error.message}"
  end

  private

  def customer_params
    params.permit(:full_name, :contact_number, :email_id)
  end

  def card_token_params
    params.permit(:card_number, :exp_year, :exp_month, :cvv)
  end
end

app/views/admin/bookings/index.html.erb
<div class="col-lg-12 mt-5">
  <div class="card mt-5 mb-5">
    <div class="card-body">
      <%= search_form_for @q, url: admin_bookings_path do |f| %>
        <h4>Search from Booking Attributes</h4>
        <div class="row mt-3 mb-3">
          <div class="col-lg-4">
            <div class="form-group">
              <%= f.label :order_number %>
              <%= f.search_field :order_number_cont, class: 'form-control mt-2 mb-2' %>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="form-group">
              <%= f.label :amount_paid_eq %>
              <%= f.search_field :amount_paid_eq, class: 'form-control mt-2 mb-2' %>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="form-group">
              <%= f.label :amount_paid_lteq %>
              <%= f.search_field :amount_paid_lteq, class: 'form-control mt-2 mb-2' %>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="form-group">
              <%= f.label :amount_paid_gteq %>
              <%= f.search_field :amount_paid_gteq, class: 'form-control mt-2 mb-2' %>
            </div>
          </div>
        </div>

        <h4>Search from Workshop Attributes</h4>
        <div class="row mt-3 mb-3">
          <div class="col-lg-4">
            <div class="form-group">
              <%= f.label :name %>
              <%= f.search_field :workshop_name_cont, class: 'form-control mt-2 mb-2' %>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="form-group">
              <%= f.label :workshop_start_date_eq %>
              <%= f.date_field :workshop_start_date_eq, class: 'form-control mt-2 mb-2' %>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="form-group">
              <%= f.label :workshop_end_date %>
              <%= f.date_field :workshop_end_date_eq, class: 'form-control mt-2 mb-2' %>
            </div>
          </div>
        </div>

        <h4>Search from Customer Attributes</h4>
        <div class="row mt-3 mb-3">
          <div class="col-lg-4">
            <div class="form-group">
              <%= f.label :customer_name %>
              <%= f.search_field :customer_full_name_cont, class: 'form-control mt-2 mb-2' %>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="form-group">
              <%= f.label :customer_email %>
              <%= f.search_field :customer_email_id_cont, class: 'form-control mt-2 mb-2' %>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="form-group">
              <%= f.label :customer_contact %>
              <%= f.search_field :customer_contact_number_cont, class: 'form-control mt-2 mb-2' %>
            </div>
          </div>
        </div>

        <%= f.submit class: "btn btn-primary mt-4" %>
        <%= link_to "Reset Search", admin_bookings_path, class: "btn btn-primary mt-4" %>
      <% end %>
    </div>
  </div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Booking ID</th>
        <th>Customer</th>
        <th>Workshop</th>
        <th>Amount Paid</th>
        <th>Tickets Booked</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @bookings.each do |booking| %>
        <tr>
          <td><%= booking.order_number %></td>
          <td><%= link_to booking.customer.full_name, admin_customer_path(booking.customer) %></td>
          <td><%= link_to booking.workshop.name, admin_workshop_path(booking.workshop) %></td>
          <td><%= booking.amount_paid %></td>
          <td><%= booking.no_of_tickets %></td>
          <td>
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                Actions
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><%= link_to "View", admin_booking_path(booking), class: "dropdown-item" %></li>
                <li><%= link_to "Delete", admin_booking_path(booking), class: "dropdown-item", data: { confirm: 'Are you sure you want to delete this booking?', method: :delete } %></li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/bookings/show.html.erb
<div class="col-lg-12 mt-5">
  <%= link_to "Back to Dashboard", admin_dashboard_path, class: "btn btn-primary shadow" %>
  <%= link_to "View All Bookings", admin_bookings_path, class: "btn btn-primary shadow" %>
  <div class="row mt-5">
    <div class="col-lg-7">
      <div class="card shadow">
        <div class="card-body">
          <h4 class="card-title"><%= @workshop.name %></h4>
          <p  class="lead"><%= @workshop.description %></p>
          <h4><span class="badge bg-primary"><%= @workshop.total_duration%></span></h4>
          <h4><span class="badge bg-primary"><%= @workshop.daily_duration %></span></h4>
          <p class="lead"> Total Sits: <span class="badge bg-primary"><%= @workshop.total_sits %></span></p>
          <p class="lead"> Remaining Sits: <span class="badge bg-primary"><%= @workshop.remaining_sits %></span></p>
          <p class="lead"> Registration Fee: <span class="badge bg-primary"><%= @workshop.registration_fee %></span></p>
        </div>
      </div>
    </div>
    <div class="col-lg-5">
      <div class="card shadow">
        <div class="card-body">
          <h4 class="card-title">Customer Details</h4>
          <hr>
          <p class="lead"><strong>Name: </strong><%= @customer.full_name %></p>
          <p class="lead"><strong>Email: </strong><%= @customer.email_id %></p>
          <p class="lead"><strong>Contact No.</strong><%= @customer.contact_number %></p>
        </div>
      </div>
    </div>
  </div>
</div>