config/routes.rb
Rails.application.routes.draw do
 devise_for :admin_users, controllers: {
    sessions: 'admin_user/sessions',
    passwords: 'admin_user/passwords'
  }
  #get 'bookings/create'
  root 'home#index'
  resources :workshops, only: %i[index show]
  resources :bookings, only: %i[create] do
  	get :booking_details, on: :member
  end

  resources :refunds do
    get :refund_acceptance, on: :member
  end
  

  namespace :admin do
  	 get 'dashboard' => 'dashboard#index'
     resources :workshops
     resources :bookings
     resources :customers
     resources :refunds do 
      member do
        patch :process_refund
      end
     end
  	end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController
 def index
   @workshop_count = Workshop.count
   @upcoming_workshop_count = Workshop.upcoming_workshops.count
   @past_workshop_count = Workshop.past_workshops.count
   @customer_count = Customer.count
   @booking_count = Booking.count
   @revenue_earned = Booking.pluck(:amount_paid).sum

   @refundable_bookings =  @refundable_booking = Booking.includes(:workshop).where('Workshops.start_date >= ?', Date.today).references(:workshops)
   @active_refunds = Refund.includes(:booking).where('bookings.workshop_id IN (?) AND refunds.state = ?', Workshop.upcoming_workshops.ids, 'accepted').references(:booking)
 end
end 

app/views/admin/dashboard/index.html.erb
<div class="col-lg-6">
	<div class="card shadow mt-5">
		<div class="card-body">
			<p class="lead"><%= @workshop_count %> Total Workshops</p>
			<p class="lead"><%= @upcoming_workshop_count %> Upcoming Workshops</p>
			<p class="lead"><%= @past_workshop_count %>  Workshops Organized Recently  </p>
			<%= link_to 'View All Workshops', admin_workshops_path, class: "btn btn-primary"%>
		</div>
	</div>
</div>
<div class="col-lg-6">
	<div class="card shadow mt-5">
		<div class="card-body">
			<p class="lead"><%= @booking_count %> Total Bookings </p>
			<p class="lead">$<%= @revenue_earned %> Total Revenue </p>
			<%= link_to 'View All Bookings', admin_bookings_path, class: "btn btn-primary"%>
		</div>
	</div>
</div>
<div class="col-lg-6">
	<div class="card shadow mt-5">
		<div class="card-body">
			<p class="lead"><%= @customer_count %>  Total Customers</p>
			<%= link_to 'View All Customers', admin_customers_path, class: "btn btn-primary"%>
		</div>
	</div>
</div>


<div class="col-lg-6">
	<div class="card shadow mt-5">
		<div class="card-body">
			<p class="lead fw-bold"><%= @refundable_bookings.count %>
				Refundable Bookings
			</p>
			<% @refundable_bookings.each do |booking| %>
			 <p class="lead"><%= link_to booking.workshop.name, admin_booking_path(booking) %></p>
			<% end %>
		</div>
	</div>
</div>

<div class="col-lg-6">
	<div class="card shadow mt-5">
		<div class="card-body">
			<p class="lead fw-bold"><%=  @active_refunds.count %>
				Refundable to be  processed
			</p>
			<ul class="list-group">
			<% @active_refunds.each do |refund|%> 
             <li class="list-group-item">
             	<p class="lead"> <%= link_to refund.booking.workshop.name, admin_workshop_path(refund.booking.workshop)%></p>
                <p class="lead"><%= refund.no_of_tickets%> tickets ($ <%= refund. amount_to_be_refunded%>) to be refund</p>
                <%= link_to "Process Refund", process_refund_admin_refund_path(refund), class: "btn btn-primary", method: :patch %>
             </li>
            <% end %>
			</ul>
		</div>
	</div>
</div>