config/routes.rb
Rails.application.routes.draw do
 devise_for :admin_users, controllers: {
    sessions: 'admin_user/sessions',
    passwords: 'admin_user/passwords'
  }
  #get 'bookings/create'
  root 'home#index'
  resources :workshops, only: %i[index show]
  resources :bookings, only: %i[create] do
  	get :booking_details, on: :member
  end

  resources :refunds do
    get :refund_acceptance, on: :member
  end
  

  namespace :admin do
  	 get 'dashboard' => 'dashboard#index'
     resources :workshops
     resources :bookings
     resources :customers
     resources :refunds do 
      member do
        patch :process_refund
      end
     end
  	end
end

app/views/shared/_flash.html.erb
<div id="flash">
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key.to_sym) %> alert-dismissible fade show" role="alert">
      <% unless value == true %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <%= value %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Webinari', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if admin_user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Dashboard', admin_dashboard_path, class: "nav-link active"  %>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', destroy_admin_user_session_path, method: :delete, class: "nav-link active"  %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'Refund ', new_refund_path, class: "nav-link active"  %>
        </li>
        <li class="nav-item">
          <%= link_to 'Admin', new_admin_user_session_path, class: "nav-link active"  %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_workshops.html.erb
<h3 class="mt-4 mb-4"><%= section_title %></h3>
<div class="row">
 <% workshops.each do |workshop| %>
    <div class="col-lg-6">
     <div class="card shadow mb-3 mt-2 ">
       <div class="card-body">
          <h4 class="card-title"><%= workshop.name %></h4>
          <p class="lead"><%= truncate(workshop.description, length: 50) %></p>
          <h4><span class="badge bg-primary"><%= workshop.total_duration%></span></h4>
          <h4><span class="badge bg-primary"><%= workshop.daily_duration %></span></h4>
          <%= link_to 'View Details ', workshop, class:"btn btn-danger btn-lg" %>
        </div>
      </div>
    </div>
 <%end%>
<div>